/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by cataloggen; DO NOT EDIT.

package catalog

import "encoding/json"

const (
	Version              = "1.0.0"
	MinimumClientVersion = "1.0.0"
	SourceSHA256         = "96296f0aacedd922ccfb075dda39fab90e80e92e68621bed7d4a3c27221745aa"
)

var generatedTools = []Tool{
	{
		Name:                 "rmq.capabilities",
		CLI:                  CLI{Resource: "capabilities", Verb: "get"},
		Description:          "Describe the capabilities of one RocketMQ cluster.",
		RiskLevel:            "L1",
		Permission:           "cluster:read",
		RequiredCapabilities: []string{},
		InputSchema:          mustSchema("{\"additionalProperties\":false,\"properties\":{\"cluster\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"cluster\"],\"type\":\"object\"}"),
		OutputSchema:         mustSchema("{\"additionalProperties\":false,\"properties\":{\"capabilities\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"cluster\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"},\"version\":{\"type\":\"string\"}},\"required\":[\"cluster\",\"type\",\"version\",\"capabilities\"],\"type\":\"object\"}"),
		ViewHint:             "object",
		Deprecated:           false,
	},
	{
		Name:                 "rmq.cluster.list",
		CLI:                  CLI{Resource: "cluster", Verb: "list"},
		Description:          "List RocketMQ clusters available in Studio.",
		RiskLevel:            "L1",
		Permission:           "cluster:read",
		RequiredCapabilities: []string{},
		InputSchema:          mustSchema("{\"additionalProperties\":false,\"type\":\"object\"}"),
		OutputSchema:         mustSchema("{\"items\":{\"additionalProperties\":false,\"properties\":{\"id\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"status\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"},\"version\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"type\",\"status\",\"version\"],\"type\":\"object\"},\"type\":\"array\"}"),
		ViewHint:             "table",
		Deprecated:           false,
	},
}

func mustSchema(source string) map[string]any {
	var schema map[string]any
	if err := json.Unmarshal([]byte(source), &schema); err != nil {
		panic(err)
	}
	return schema
}
