# Development profile
logging:
  level:
    com.rocketmq.studio: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: INFO
