/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunGeneratesAndVerifiesCatalog(t *testing.T) {
	directory := t.TempDir()
	input := filepath.Join(directory, "rmq-tools.yaml")
	output := filepath.Join(directory, "catalog_gen.go")
	source := `version: 1.0.0
minimumClientVersion: 1.0.0
tools:
  - name: rmq.cluster.list
    cli:
      resource: cluster
      verb: list
    description: List clusters.
    riskLevel: L1
    permission: cluster:read
    requiredCapabilities: []
    inputSchema:
      type: object
      required:
        - cluster
      properties:
        cluster:
          type: string
          minLength: 1
        status:
          type: string
          minLength: 1
    outputSchema:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
    viewHint: table
`
	if err := os.WriteFile(input, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}

	arguments := []string{"-input", input, "-output", output}
	if err := run(arguments); err != nil {
		t.Fatalf("generate catalog: %v", err)
	}
	generated, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, expected := range []string{
		"Code generated by cataloggen. DO NOT EDIT.",
		`Name:                 "rmq.cluster.list"`,
		`Permission:           "cluster:read"`,
		`RequiredCapabilities: []string{}`,
		`{Name: "cluster", Flag: "cluster", Kind: StringField, Required: true, MinLength: 1}`,
		`{Name: "status", Flag: "status", Kind: StringField, MinLength: 1}`,
		`TableDataKey: "items"`,
	} {
		if !strings.Contains(text, expected) {
			t.Fatalf("generated catalog does not contain %q\n%s", expected, text)
		}
	}

	if err := run(append(arguments, "-check")); err != nil {
		t.Fatalf("verify generated catalog: %v", err)
	}
}
