/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const instanceScopedToolSource = `version: 1.0.0
minimumClientVersion: 1.0.0
tools:
  - name: rmq.topic.list
    cli:
      resource: topic
      verb: list
    description: List topics.
    riskLevel: L1
    permission: topic:read
    requiredCapabilities: []
    inputSchema:
      type: object
      required:
        - instanceId
      properties:
        instanceId:
          type: string
          minLength: 1
        topicName:
          type: string
          minLength: 1
    outputSchema:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
    viewHint: table
`

const platformToolSource = `version: 1.0.0
minimumClientVersion: 1.0.0
tools:
  - name: rmq.cluster.list
    cli:
      resource: cluster
      verb: list
    description: List clusters.
    riskLevel: L1
    permission: cluster:read
    requiredCapabilities: []
    inputSchema:
      type: object
      properties:
        status:
          type: string
          minLength: 1
    outputSchema:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
    viewHint: table
`

func writeCatalogSource(t *testing.T, source string) (input string, output string) {
	t.Helper()
	directory := t.TempDir()
	input = filepath.Join(directory, "rmq-tools.yaml")
	output = filepath.Join(directory, "catalog_gen.go")
	if err := os.WriteFile(input, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	return input, output
}

func TestRunGeneratesAndVerifiesCatalog(t *testing.T) {
	input, output := writeCatalogSource(t, instanceScopedToolSource)

	arguments := []string{"-input", input, "-output", output}
	if err := run(arguments); err != nil {
		t.Fatalf("generate catalog: %v", err)
	}
	generated, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, expected := range []string{
		"Code generated by cataloggen. DO NOT EDIT.",
		`Name:                 "rmq.topic.list"`,
		`Permission:           "topic:read"`,
		`RequiredCapabilities: []string{}`,
		`{Name: "instanceId", Flag: "instance-id", Kind: StringField, Required: true, MinLength: 1}`,
		`{Name: "topicName", Flag: "topic-name", Kind: StringField, MinLength: 1}`,
		`TableDataKey: "items"`,
	} {
		if !strings.Contains(text, expected) {
			t.Fatalf("generated catalog does not contain %q\n%s", expected, text)
		}
	}

	if err := run(append(arguments, "-check")); err != nil {
		t.Fatalf("verify generated catalog: %v", err)
	}
}

// TestRunAcceptsPlatformToolWithoutInstanceID verifies the platform-level
// exemption list (decisions 25/26): exempt tools must not declare instanceId.
func TestRunAcceptsPlatformToolWithoutInstanceID(t *testing.T) {
	input, output := writeCatalogSource(t, platformToolSource)
	if err := run([]string{"-input", input, "-output", output}); err != nil {
		t.Fatalf("generate catalog: %v", err)
	}
	generated, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(generated), "instanceId") {
		t.Fatalf("platform tool catalog must not carry instanceId:\n%s", generated)
	}
}

// TestRunRejectsInstanceScopedToolWithoutInstanceID verifies that non-platform
// tools must declare and require instanceId (decision 7).
func TestRunRejectsInstanceScopedToolWithoutInstanceID(t *testing.T) {
	source := strings.Replace(instanceScopedToolSource, `      required:
        - instanceId
      properties:
        instanceId:
          type: string
          minLength: 1
`, `      properties:
`, 1)
	input, output := writeCatalogSource(t, source)
	err := run([]string{"-input", input, "-output", output})
	if err == nil || !strings.Contains(err.Error(), "must declare instanceId") {
		t.Fatalf("err = %v, want instanceId declaration failure", err)
	}
}

// TestRunRejectsPlatformToolDeclaringInstanceID verifies the exemption is
// bidirectional: platform-level tools must not declare instanceId.
func TestRunRejectsPlatformToolDeclaringInstanceID(t *testing.T) {
	source := strings.Replace(platformToolSource, `    inputSchema:
      type: object
      properties:
`, `    inputSchema:
      type: object
      required:
        - instanceId
      properties:
        instanceId:
          type: string
          minLength: 1
`, 1)
	input, output := writeCatalogSource(t, source)
	err := run([]string{"-input", input, "-output", output})
	if err == nil || !strings.Contains(err.Error(), "must not declare instanceId") {
		t.Fatalf("err = %v, want platform-tool instanceId rejection", err)
	}
}

// TestRunCompilesClientDefaultNow verifies the x-client-default: NOW catalog
// extension (decision 13) is parsed, validated and compiled into the generated
// Field so the runtime can fill the current Unix milliseconds.
func TestRunCompilesClientDefaultNow(t *testing.T) {
	source := strings.Replace(instanceScopedToolSource, `        topicName:
          type: string
          minLength: 1
`, `        timestamp:
          type: integer
          x-client-default: NOW
`, 1)
	source = strings.Replace(source, `      required:
        - instanceId
`, `      required:
        - instanceId
        - timestamp
`, 1)
	input, output := writeCatalogSource(t, source)
	if err := run([]string{"-input", input, "-output", output}); err != nil {
		t.Fatalf("generate catalog: %v", err)
	}
	generated, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	expected := `{Name: "timestamp", Flag: "timestamp", Kind: IntegerField, Required: true, ClientDefault: "NOW"}`
	if !strings.Contains(string(generated), expected) {
		t.Fatalf("generated catalog does not contain %q\n%s", expected, generated)
	}
}

// TestRunRejectsUnsupportedClientDefault verifies that only NOW is accepted
// for x-client-default.
func TestRunRejectsUnsupportedClientDefault(t *testing.T) {
	source := strings.Replace(instanceScopedToolSource, `        topicName:
          type: string
          minLength: 1
`, `        timestamp:
          type: integer
          x-client-default: TODAY
`, 1)
	input, output := writeCatalogSource(t, source)
	err := run([]string{"-input", input, "-output", output})
	if err == nil || !strings.Contains(err.Error(), "unsupported x-client-default") {
		t.Fatalf("err = %v, want unsupported x-client-default failure", err)
	}
}

// TestRunRejectsNestedClientDefault verifies that x-client-default is only
// allowed on top-level properties, matching the runtime fill scope.
func TestRunRejectsNestedClientDefault(t *testing.T) {
	source := strings.Replace(instanceScopedToolSource, `        topicName:
          type: string
          minLength: 1
`, `        filter:
          type: object
          properties:
            timestamp:
              type: integer
              x-client-default: NOW
`, 1)
	input, output := writeCatalogSource(t, source)
	err := run([]string{"-input", input, "-output", output})
	if err == nil || !strings.Contains(err.Error(), "only supported on top-level properties") {
		t.Fatalf("err = %v, want nested x-client-default failure", err)
	}
}

// TestRunRejectsReservedInstanceIDFlag verifies that per-tool properties
// cannot claim the global --instance-id flag, neither via x-cli-flag nor via
// a nested property literally named instanceId.
func TestRunRejectsReservedInstanceIDFlag(t *testing.T) {
	source := strings.Replace(instanceScopedToolSource, `        topicName:
          type: string
          minLength: 1
`, `        topicName:
          type: string
          minLength: 1
          x-cli-flag: instance-id
`, 1)
	input, output := writeCatalogSource(t, source)
	err := run([]string{"-input", input, "-output", output})
	if err == nil || !strings.Contains(err.Error(), "reserved CLI flag --instance-id") {
		t.Fatalf("err = %v, want reserved flag failure", err)
	}

	nested := strings.Replace(instanceScopedToolSource, `        topicName:
          type: string
          minLength: 1
`, `        filter:
          type: object
          properties:
            instanceId:
              type: string
`, 1)
	input, output = writeCatalogSource(t, nested)
	err = run([]string{"-input", input, "-output", output})
	if err == nil || !strings.Contains(err.Error(), "reserved CLI flag --instance-id") {
		t.Fatalf("err = %v, want nested instanceId rejection", err)
	}
}
